server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/bryceyang/Documents/workspace/git-local-repo
      label: main